apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  selector:
    app.kubernetes.io/name: coworking-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-api
  labels:
    name: coworking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-api
  template:
    metadata:
      labels:
        service: coworking-api
    spec:
      containers:
      - name: coworking-api
        image: 758716314495.dkr.ecr.us-east-1.amazonaws.com/lqdisme-project-3:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 50
          timeoutSeconds: 50
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 50
          timeoutSeconds: 50
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: APP_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
      restartPolicy: Always